ARG ARGOCD_VERSION=3.5.3
RUN curl -fsSL "https://github.com/argoproj/argo-cd/releases/download/v${ARGOCD_VERSION}/argocd-linux-${TARGETARCH}" -o /usr/local/bin/argocd \
 && chmod 0755 /usr/local/bin/argocd
