ARG SCW_VERSION=2.62.0
RUN curl -fsSL "https://github.com/scaleway/scaleway-cli/releases/download/v${SCW_VERSION}/scaleway-cli_${SCW_VERSION}_linux_${TARGETARCH}" -o /usr/local/bin/scw \
 && chmod 0755 /usr/local/bin/scw
